### PR TITLE
Adds denoms to balance

### PR DESCRIPTION
**Pull request by ducksquaddd**
Also adds the chains denom under params in state.

### CODE REVIEW

**Comment by angrymouse** [comment]
@ducksquaddd I think we might also want to allow specifying denoms in gas

**Comment by ducksquaddd** [comment]
@angrymouse personally I think it would be better just to keep it the native asset as then we would need add extra gas params for each tokens fee, etc, etc

**Comment by ducksquaddd** [comment]
@angrymouse unless we redid the gas system

**Comment by angrymouse** [comment]
@ducksquaddd yeah I think it would be cool to allow specifying denoms in gas params as well. Or just make default denom when paying gas, right now it just tries to overwrite whole object with denoms (as earlier)

**Comment by ducksquaddd** [comment]
@angrymouse i feel like that would just add more complexity to gas params though lol

**Comment by angrymouse** [comment]
@ducksquaddd Yeah true... Can leave it as it is for now. LGTM

**Comment by ducksquaddd** [comment]
@angrymouse thank god didnt feel like going through all that lmao

**Pull request merged**
